name = "mr-robot-dashboard"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "artifacts/dashboard/dist/public"

[[durable_objects.bindings]]
name = "EVENT_BUS"
class_name = "EventBus"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["EventBus"]
